### PR TITLE
Initial SHACL shape for validating Loc-I conformant Features

### LINKED ISSUE #8: SHACL validation of loci:Feature
Create SHACL graph for initial validation of Loc-I conformant features

### PR DESCRIPTION
**Pull request by dr-shorthair**
resolves #8

### CODE REVIEW

**Comment by jyucsiro** [comment]
Looks good overall. i've been able to test it on an example (see below):
[mb1.zip](https://github.com/CSIRO-enviro-informatics/loci-ont/files/4272744/mb1.zip)

i'm having trouble validating using pySHACL and https://shacl.org/playground/ because there is an assumption that the "Data Graph" will include the relevant ontologies and other data graphs. If they are not included, the validation reports return violations e.g....

```
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n263 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/meshblock/> ;
	sh:resultPath loci:isMemberOf ;
	sh:resultMessage "Value does not have class loci:Dataset" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n265 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/def/asgs-cat/45> ;
	sh:resultPath dcterms:type ;
	sh:resultMessage "Value does not have class skos:Concept" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n266 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://gds.loci.cat/geometry/asgs16_mb/50055290000> ;
	sh:resultPath geo:hasGeometry ;
	sh:resultMessage "Value does not have class geo:Geometry" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/destinationzone/511311450> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/localgovernmentarea/51330> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/naturalresourcemanagementregion/503> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/stateorterritory/WA> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/statesuburb/51595> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
[
	a sh:ValidationResult ;
	sh:resultSeverity sh:Violation ;
	sh:sourceConstraintComponent sh:ClassConstraintComponent ;
	sh:sourceShape _:n269 ;
	sh:focusNode <http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> ;
	sh:value <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/50603113101> ;
	sh:resultPath geo:sfWithin ;
	sh:resultMessage "Value does not have class geo:Feature" ;
] .
```

**Comment by ashleysommer** [comment]
Hi @jyucsiro
Have a look at the "extra ontology" feature in pySHACL to solve that problem.

Note, you can only specify _one_ extra ontology file, but you use owl:imports statements within it to source point of truth ontologies to mix into the validation.

**Comment by jyucsiro** [comment]
thanks @ashleysommer 

i tried adding either the loci ontology as the "extra ontology file" with the imports function (see below - me using pyshacl windows version cli). looks like i'm hitting a SSL certificate error.
```
$ pyshacl.exe -s loci.shapes.ttl -e loci.ttl  -m --imports -i rdfs -a -f human mb1.ttl                                                          

[1752] Failed to execute script cli  
Traceback (most recent call last):  
File "urllib\request.py", line 1317, in do_open 
File "http\client.py", line 1229, in request                                                                                                                                      
File "http\client.py", line 1275, in _send_request                                                                                                                                
File "http\client.py", line 1224, in endheaders                                                                                                                                   
File "http\client.py", line 1016, in _send_output                                                                                                                                 
File "http\client.py", line 956, in send                                                                                                                                          
File "http\client.py", line 1392, in connect                                                                                                                                      
File "ssl.py", line 412, in wrap_socket                                                                                                                                           
File "ssl.py", line 853, in _create                                                                                                                                               
File "ssl.py", line 1117, in do_handshake                                                                                                                                       
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1056)                                                                                                                                                                                                                                     

During handling of the above exception, another exception occurred:                                                                                                                                                                                                                                                                                                 
Traceback (most recent call last):                                                                                                                                                  
File "pyshacl\cli.py", line 117, in                                                                                                                                       
File "pyshacl\cli.py", line 82, in main                                                                                                                                           
File "pyshacl\validate.py", line 266, in validate                                                                                                                                 
File "pyshacl\rdfutil\load.py", line 284, in load_from_source                                                                                                                     
File "pyshacl\rdfutil\load.py", line 284, in load_from_source                                                                                                                     
File "pyshacl\rdfutil\load.py", line 284, in load_from_source                                                                                                                     
File "pyshacl\rdfutil\load.py", line 101, in load_from_source                                                                                                                     
File "pyshacl\rdfutil\load.py", line 25, in get_rdf_from_web                                                                                                                      
File "urllib\request.py", line 222, in urlopen                                                                                                                                    
File "urllib\request.py", line 531, in open                                                                                                                                       
File "urllib\request.py", line 641, in http_response                                                                                                                              
File "urllib\request.py", line 563, in error                                                                                                                                      
File "urllib\request.py", line 503, in _call_chain                                                                                                                                
File "urllib\request.py", line 755, in http_error_302                                                                                                                             
File "urllib\request.py", line 531, in open                                                                                                                                       
File "urllib\request.py", line 641, in http_response                                                                                                                              
File "urllib\request.py", line 563, in error                                                                                                                                      
File "urllib\request.py", line 503, in _call_chain                                                                                                                                
File "urllib\request.py", line 755, in http_error_302                                                                                                                             
File "urllib\request.py", line 525, in open                                                                                                                                       
File "urllib\request.py", line 543, in _open                                                                                                                                      
File "urllib\request.py", line 503, in _call_chain                                                                                                                                
File "urllib\request.py", line 1360, in https_open                                                                                                                                
File "urllib\request.py", line 1319, in do_open                                                                                                                                 
urllib.error.URLError:

```

I also tried the ASGS ontology like this:
```
$ pyshacl.exe -s loci.shapes.ttl -e asgs.ttl  -m --imports -i rdfs -f human mb1.ttl                                                          
```
But same SSL errors...

That aside, there is a general problem of providing as input, a data graph with URI refs to other resources with the information to resolve. In the example file, the resource is an asgs:MeshBlock
```
<http://linked.data.gov.au/dataset/asgs2016/meshblock/50055290000> a asgs:Feature,
        asgs:MeshBlock,
        geo:Feature ;
... snip ...
    loci:isMemberOf <http://linked.data.gov.au/dataset/asgs2016/meshblock/> ;
    dcterms:type <http://linked.data.gov.au/def/asgs-cat/45> ;
    geo:hasGeometry <http://gds.loci.cat/geometry/asgs16_mb/50055290000> ;
    geo:sfWithin <http://linked.data.gov.au/dataset/asgs2016/destinationzone/511311450>,
        <http://linked.data.gov.au/dataset/asgs2016/localgovernmentarea/51330>,
        <http://linked.data.gov.au/dataset/asgs2016/naturalresourcemanagementregion/503>,
        <http://linked.data.gov.au/dataset/asgs2016/stateorterritory/WA>,
        <http://linked.data.gov.au/dataset/asgs2016/statesuburb/51595>,
        <http://linked.data.gov.au/dataset/asgs2016/statisticalarealevel1/50603113101> 
.
```
The data graph could be valid, but the SHACL parser would need to pull in those resources to validate the graph... or the submitter has to manually add them in (not ideal).

**Comment by dr-shorthair** [comment]
The tests that are really biting are where the value of a property is URI-reference to a remotely-hosted resource. All the errors in https://github.com/CSIRO-enviro-informatics/loci-ont/pull/9#issuecomment-593164975 are where the `rdf:type` of a remote resource is not known. They all go away if you add those into the dataset of course. Cross-references across the web are not type-safe, so I've adjusted the 'severity' of these tests to `sh:Info` only,

**Comment by dr-shorthair** [comment]
Note I've removed all tests related to geosparql properties. Now it only tests the essential Loc-I conformance criteria, as documented on http://loci.cat/loci-datasets

**Pull request merged**
